### ISSUE TITLE
Paxel dont switch sometimes

### ISSUE THREAD

**Issue by amarcais53** [NCBPFluffyBear/FluffyMachines#102]
## Description (Required)
when i use the paxel sometimes it doesnt switch the the good tool and i need to click again to get the tool switching

## Steps to reproduce the Issue (Required)
idk how to reproduce it im just destroying the OneBlock its a gamemode from bentobox and when u break a block a new one appear
https://www.youtube.com/watch?v=xsVSDgxByTo there is a youtube video to show the bug
## Expected behavior (Required)
the paxel should switch to the good tool

## Server Log / Error Report
there is no errors

## Environment (Required)
Purpur git-Purpur-1421 (MC: 1.17.1)
Slimefun DEV - 984 (git 82978f7d)
Metrics-Module #28
Java 16

Installed Addons: (4)
  CMILib v1.0.4.3
  FluffyMachines vDEV - 91 (git 7137659b)
  CMI v9.0.6.3
  HeadLimiter vDEV - 11 (git 7da34068)

**Comment by amarcais53** [comment]
ok after some testing the issue is there only when there is unbreaking on the tool
if i remove unbreaking the bug disapear

**Comment by NCBPFluffyBear** [comment]
Determined to be a OneBlock issue.

**Comment by amarcais53** [comment]
hey @NCBPFluffyBear as we talked before the fix should have fixed the issue but unfortunatly it isnt here is my version 
![image](https://user-images.githubusercontent.com/62488520/178038869-b1799780-95b1-4186-a713-ebae1c3d5530.png)

**Comment by amarcais53** [comment]
https://user-images.githubusercontent.com/62488520/178039178-a1de5272-332a-4d58-956c-9c26d035e20a.mp4
