### ISSUE TITLE
Backpack loader dupes items

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FluffyMachines#104]
## Description (Required)

Fluffy, just watch the video. it will explain exactly what I did and how easy it is.

## Steps to reproduce the Issue (Required)

https://youtu.be/5oxCZ7o-rCw

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version: dev 987
 - FluffyMachines Version: 94

**Comment by NCBPFluffyBear** [comment]
Determined to be a Slimefun issue

**Comment by NCBPFluffyBear** [comment]
https://github.com/Slimefun/Slimefun4/issues/3379
