### ISSUE TITLE
Unable to activate foundry due to lacking permission

### ISSUE THREAD

**Issue by marvjosh1** [NCBPFluffyBear/FluffyMachines#107]
## Description (Required)
When clicking the superheated furnace of a foundry with lava, it gives the message that you dont have permission to use the block

## Steps to reproduce the Issue (Required)
https://youtu.be/SJGEANKfMyI

## Expected behavior (Required)
For the foundry to be activated and accessable

## Server Log / Error Report
n/a

## Environment (Required)
https://i.imgur.com/DUURSSu.png
https://i.imgur.com/ZIiKodO.png

**Comment by NCBPFluffyBear** [comment]
Fixed in 657bd98
