### ISSUE TITLE
[Feature request] Max level config for Auto Disenchanter

### ISSUE THREAD

**Issue by Sfiguz7** [NCBPFluffyBear/FluffyMachines#109]
## Description
Currently, there is a config option in core Slimefun for a maximum enchantment level (shared for all enchantments, not one setting per) over which an item put in the Enchanters and Disenchanters will be rejected and the process simplywon't not start. Granted the option is turned off by default, there is no way to config the Advanced Auto Disenchanter to follow suit if one were to decide to have the limitation in place.
What this feature request aims to do is to ask for a similar limitation to be in place, so that only enchantments below the configured maximum level can actually be moved to Ancient Books while the others are ignored by the cycling feature (or are rejected in some way)

## Proposed additions
- Add a config option for an overall enchantment limitation similar to core Enchanters and Disenchanters (see image attached)
- Add a config option to enable/disable the aforementioned setting, to allow current behavior to persist for existing servers

##

Example image of core's Auto Enchanter set configured in a way that does not allow books with enchantments above lvl 15 from being applied to tools:
![image](https://user-images.githubusercontent.com/37039432/151050824-3aa4f8ef-271e-4e19-bb53-4ddff0145b80.png)

**Comment by NCBPFluffyBear** [comment]
Added in 657bd98

**Comment by Sfiguz7** [comment]
Um. Could it be you meant #107?

**Comment by NCBPFluffyBear** [comment]
Wrong commit tag, fixed
