### ISSUE TITLE
Auto Enchanter enchant-level-limit fetus deletus

### ISSUE THREAD

**Issue by Azakaturan** [NCBPFluffyBear/FluffyMachines#111]
As per discord:

Set the enchant-level-limit to 15, put the Blade of the Cosmos into it, take the first 2 enchants (Fire aspect and looting) off normally.  Once those are off, it doesn't even see the sharpness and then disappears
![unknown](https://user-images.githubusercontent.com/79327162/153987319-fbc3286b-a7f2-43fc-87d4-2e66bdb39db2.png)
![unknown](https://user-images.githubusercontent.com/79327162/153987324-9eb5a308-4c22-4044-9279-d66791f4f3e0.png)
![unknown](https://user-images.githubusercontent.com/79327162/153987331-5936dd8a-61eb-4716-87d7-22f071d03492.png)
.

**Comment by NCBPFluffyBear** [comment]
Fixed in af2aa94
