### ISSUE TITLE
The electric dust fabricator doesnt work

### ISSUE THREAD

**Issue by HelloBoss123** [NCBPFluffyBear/FluffyMachines#117]
## Description (Required)
After I place the electric dust fabricator with my energy rewgulator and solar panel it disapears when the 4th dust gets 
produced

place energy regulator solar panel and the electricc dust fabricator
then take the dust out when u put cobble

not disapear and instead give me my dust 

## Environment (Required)
![image](https://user-images.githubusercontent.com/104096109/164323874-b89e619c-192f-47a8-bd4b-3b15f1fe33be.png)

 - Minecraft Version: 1.18.2
 - CS-CoreLib Version: -
 - Slimefun Version: DEV - 1010 (git 217196c1)
 - FluffyMachines Version: vDEV - 116 (git e439acf9)

**Comment by NCBPFluffyBear** [comment]
Can I have the error log? The path to it appears in console once the machine breaks.

**Comment by 100petr** [comment]
https://pastebin.com/0LnShFL0

**Comment by 100petr** [comment]
I guess it's a matter of slimefun https://github.com/Slimefun/Slimefun4/pull/3541

**Comment by NCBPFluffyBear** [comment]
Fixed in Slimefun
