### ISSUE TITLE
Turning Fluffy barrel into vanilla block

### ISSUE THREAD

**Issue by xsorencoolx** [NCBPFluffyBear/FluffyMachines#120]
## Description (Required)
hi i got problem at all of my survival seasons in every 2 - 3 months that server is running  most of the slimefun blocks turn into vanilla blocks random time and my players really mad at me because this bug i don't know what should i do really to prevent this from happening and slimefun kinda making my server lag at higher player i would really need your advice to keep my server up please help me here is my timings 
https://timings.aikar.co/?id=6ad5ceef5e6d47efa3a31bb9747b60ed

## Server Log / Error Report
don't have any error

## Environment (Required)
![image](https://user-images.githubusercontent.com/51112473/175486255-f3cf548f-27b8-48e8-a267-988275e61720.png)
 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: dont have
 - Slimefun Version: vDev 1015 git 
 - FluffyMachines Version: vDEV 118 git 23a

**Comment by NCBPFluffyBear** [comment]
Hi, could you try using `/sf debug fish` and right click the blocks that have reverted to vanilla blocks? There should be some data about the block in chat, please screenshot it and send it here.

**Comment by xsorencoolx** [comment]
ok i did it but nothing showing in chat on that block

**Comment by NCBPFluffyBear** [comment]
Since this issue is affecting all Slimefun blocks and not just barrels, you would probably have more luck posting this issue on the Slimefun GitHub.

**Comment by NCBPFluffyBear** [comment]
Closing because of relevance
