### ISSUE TITLE
Dynatech ancient alter recipes do not work in the ancient alter

### ISSUE THREAD

**Issue by JasperChaseTOQ** [NCBPFluffyBear/FluffyMachines#121]
## Description (Required)
dynatech ancient alter recipes do not work in the auto ancient altar, i have tried crafting for example the tesseracting object and my auto ancient alter is fully powered yet it will not craft when i click craft once and i have verified it is the correct recipe.

## Steps to reproduce the Issue (Required)

![2022-06-28_20 41 52](https://user-images.githubusercontent.com/103849596/176327444-29255ca6-9a7c-481e-b3ec-24e8836cc0bc.png)
![2022-06-28_20 42 00](https://user-images.githubusercontent.com/103849596/176327464-b77dd367-2975-47fa-9c70-d064bde344ad.png)
## Expected behavior (Required)

for dynatech's ancient alter recipes to work with the auto ancient alter

## Environment (Required)

 - Minecraft Version: 1.19
 - CS-CoreLib Version: null
 - Slimefun Version: 1015
 - FluffyMachines Version: 118

**Comment by NCBPFluffyBear** [comment]
Thanks for the report, sorry it took so long to fix!

**Comment by JasperChaseTOQ** [comment]
no worries :) thanks for fixing it :D
