### ISSUE TITLE
WaterSprinkler is active even after disabled

### ISSUE THREAD

**Issue by ItsSynchro** [NCBPFluffyBear/FluffyMachines#123]
## Description (Required)

When disabling the Water Sprinkler via items.YML and world-settings, the Water Sprinkler is still active if its already been placed. A workaround of this would be to set the success-chance to 0.0, however it still actively ticks. 

## Steps to reproduce the Issue (Required)

1. Disable the WATER_SPRINKER in items.yml and even world-settings

## Expected behavior (Required)

I'm hoping where when disabling it via items.YML it completely disabled the item from even ticking.

## Server Log / Error Report

I've provided a spark report indicating that the Water Sprinkler is still actively ticking. https://spark.lucko.me/Ckzn7KGFPb

## Environment (Required)

![image](https://user-images.githubusercontent.com/16171807/178029794-bad439b1-2ae2-4331-a11b-3e16170fa692.png)

**Comment by NCBPFluffyBear** [comment]
Hi, sorry about this issue. I will release a quick fix. This change will add a quick disable check at the start of the tick, so the sprinkler will still be ticking (I can't really prevent it from doing so without removing the block entirely), although its timings will be inconsequential.
