### ISSUE TITLE
Remove the Vanilla Auto Workbench. Slimefun has its own.

### ISSUE THREAD

**Issue by MagmaBro123** [NCBPFluffyBear/FluffyMachines#127]
Title. Slimefun has had its own Vanilla Auto Crafter for a while now. The Auto Magic Workbench and Smart Factory should also use it in their recipes too.

![2022-08-28_18 33 13](https://user-images.githubusercontent.com/51277766/187101868-5cd86589-a822-4b4b-925f-3798b1d76392.png)
![2022-08-28_18 33 31](https://user-images.githubusercontent.com/51277766/187101870-eb120e8b-d155-49f8-9059-f27b78b6a1d2.png)

If you want my Slimefun/addon versions for whatever reason, then here ya go.

![2022-08-28_18 34 16](https://user-images.githubusercontent.com/51277766/187101919-9395e100-efb2-4b7c-be02-c43b34607955.png)
![2022-08-28_18 34 18](https://user-images.githubusercontent.com/51277766/187101923-bc2b841c-936e-4972-84b8-12c84bcb5f36.png)

**Comment by NCBPFluffyBear** [comment]
Not sure why there's so much aggression in this "bug report"...
There are many reasons I have this machine here.
- Players have it placed down, so removing it will break all of them
- Many people (including me) prefer the single block machine look, and machines with larger profiles don't really fit in with automation lines
- This machine was added before Slimefun had its own vanilla auto-crafter, and was also one of the first machines I added. There's a little bit of nostalgia baked into this machine. This is my plugin, so I think I'm allowed to choose what stays in and what leaves.

If you have something against this machine, simply don't use it. If you are worried about the recipes, code something that prevents players from placing them down. You could even build your own version of FluffyMachines with the recipe modified.

**Comment by MagmaBro123** [comment]
No need for 2 of the same machine...
