### ISSUE TITLE
Fluffy dolly dupe

### ISSUE THREAD

**Issue by Deathbringer4641** [NCBPFluffyBear/FluffyMachines#128]
If you spam left click on a chest with the dolly it can dupe the chest creating 2 identical copies of the chest.

**Comment by NCBPFluffyBear** [comment]
Hi, I tried to reproduce this but I couldn't get it to dupe. I appreciate the bug report, but please follow the bug report template, no matter how urgent.

Some things I need:
1. Steps to reproduce, and a video if possible
2. Slimefun, FluffyMachines, and server versions
3. Any error reports or logs

Also, do you mean right click? The dolly doesn't do anything when it's left clicked with.

**Comment by Deathbringer4641** [comment]
yes i ment left click sorry, i will re-add to the server and try the dupe

**Comment by Deathbringer4641** [comment]
https://user-images.githubusercontent.com/112633057/188190814-6da2a750-94b7-475e-b8bb-5181a2bf24ae.mp4

**Comment by Deathbringer4641** [comment]
crouch and spam left click

**Comment by NCBPFluffyBear** [comment]
Once again, do you mean *right* click? Also please read my comment again and provide the other information I asked for.

**Comment by NCBPFluffyBear** [comment]
Should be fixed in latest, inactive so I am assuming this problem has been fixed.
