### ISSUE TITLE
Categories are not removed despite being empty.

### ISSUE THREAD

**Issue by VoltroXP** [NCBPFluffyBear/FluffyMachines#129]
## Description (Required)

After disabling a bunch of stuff (including hiding the disabled stuff in the guide in the item config file), the categories still remain despite being empty. For example, I disabled all the Fluffy Barrels, yet the category is still there and when clicking on it there is nothing inside.

## Steps to reproduce the Issue (Required)

Remove everything from a category, hide it from the guide, restart server, and the category should still be there dispite being empty.

## Expected behavior (Required)

Like it does for Slimefun, I expected the categories would be removed when they are empty.

## Environment (Required)

 - Minecraft Version: 1.19
 - Slimefun Version: DEV - 1035
 - FluffyMachines Version: DEV - 78

**Comment by NCBPFluffyBear** [comment]
Since these are subcategories, they will not disappear even if no items are in it.

I can't change this behavior from within my addon, so you might want to open an issue with Slimefun.

If I'm mistaken, please let me know!
