### ISSUE TITLE
Portable Chargers do not charge items in your inventory.

### ISSUE THREAD

**Issue by MagmaBro123** [NCBPFluffyBear/FluffyMachines#131]
## Description (Required)
Title. Portable Chargers do not charge items in your inventory.

## Steps to reproduce the Issue (Required)
Have a charged Portable Charger in your inventory and some kind of charge-able item. A Portable Teleporter, from base-Slimefun, for example.

![2022-12-25_21 18 46](https://user-images.githubusercontent.com/51277766/209499346-ad2b5431-76d9-4329-9efe-fb768e5c4d9d.png)
![2022-12-25_21 18 48](https://user-images.githubusercontent.com/51277766/209499348-2bc60a84-a114-44d3-a27a-4436db3edf6e.png)

## Expected behavior (Required)
Items in my inventory actually being charged.

## Server Log / Error Report
N/A

## Environment (Required)
![2022-12-25_21 19 56](https://user-images.githubusercontent.com/51277766/209499416-e292bc79-2b11-40f4-a461-31e4b15b34dc.png)
![2022-12-25_21 19 58](https://user-images.githubusercontent.com/51277766/209499419-6468a4b0-a9f8-4c03-82d3-4d768b5a611a.png)

**Comment by NCBPFluffyBear** [comment]
The portable charger does not work passively, hold it and right click to open its GUI.
