### ISSUE TITLE
蓬松机器的手摇发电机连接不上电路

### ISSUE THREAD

**Issue by undeadrival91** [NCBPFluffyBear/FluffyMachines#132]
## Description (Required)

手摇发电机连接不上电路，试过所有方位都不行
## Steps to reproduce the Issue (Required)

制作手摇发电机，发电
## Expected behavior (Required)

手摇发电机制作好后，电量只存储在发电机中，电量没有发送到电路系统中
## Server Log / Error Report

没有错误报告
## Environment (Required)

 - Minecraft Version:1.19
 - CS-CoreLib Version:
 - Slimefun Version:2022.12-release
 - FluffyMachines Version: Build 15 zh-CN(baoad) (git a024fb3)

**Comment by NCBPFluffyBear** [comment]
Please fill out the form

**Comment by undeadrival91** [comment]
> Please fill out the form

改好了，你看看

**Comment by NCBPFluffyBear** [comment]
Since you are running a fork of this plugin, the maintainer of your fork will have to adopt the changes as well.

**Comment by undeadrival91** [comment]
> Since you are running a fork of this plugin, the maintainer of your fork will have to adopt the changes as well.

我应该怎么做？

**Comment by NCBPFluffyBear** [comment]
Your fork maintainer will likely merge the modifications over after some time. You could open up an issue on their GitHub page if they do not do so.
