### ISSUE TITLE
Foundry Mistake

### ISSUE THREAD

**Issue by sweetjohnson2001** [NCBPFluffyBear/FluffyMachines#133]
## Description (Required)
When Checking how full the foundy is it shows up to 1% full (the decimal point is in the incorrect spot reading 1% at full capacity instead of 100%)
## Steps to reproduce the Issue (Required)
Open A Foundry and hover over Chest Icon
![image](https://user-images.githubusercontent.com/62167019/214760386-6ace45a9-1305-4f46-a63a-0ce1046efeb4.png)

## Expected behavior (Required)
Should Show 100% when Full and 75% when full not 1.0% and .75% respectively

## Server Log / Error Report
no errors in logs

## Environment (Required)
![image](https://user-images.githubusercontent.com/62167019/214761167-1c5cacba-b23c-400f-9101-a0b8f9e5675d.png)
![image](https://user-images.githubusercontent.com/62167019/214760722-263f05f0-4ecf-4add-a0d8-882dbe9bb2d1.png)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: N/A
 - Slimefun Version: 1024
 - FluffyMachines Version: 129

**Comment by sweetjohnson2001** [comment]
Yes Ignore the Chest Terminal addon, didn't realise my friend had added that originally
Going to Remove that now!

**Comment by NCBPFluffyBear** [comment]
Fixed in latest, thanks for the report
