### ISSUE TITLE
smart factory takes too much copper for heating coil and motor

### ISSUE THREAD

**Issue by madhusudhansj** [NCBPFluffyBear/FluffyMachines#136]
## Description (Required)
smart factory takes 50 copper dust per heating coil and 26 copper dust per motor whereas just takes 8 copper for electromagnet , it's supposed to take 11 for motor and 14 for heating coil which makes more sense

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - FluffyMachines Version:

**Comment by madhusudhansj** [comment]
![2023-07-03_10 54 18](https://github.com/NCBPFluffyBear/FluffyMachines/assets/8329158/b3d08142-d060-4953-a0b5-fcf6ffeb5ae9)
![2023-07-03_10 54 14](https://github.com/NCBPFluffyBear/FluffyMachines/assets/8329158/9d1b54f6-cd23-49d3-9987-a56e1fab80ce)
![2023-07-03_10 54 10](https://github.com/NCBPFluffyBear/FluffyMachines/assets/8329158/d9f0d720-df0d-4b7f-8499-0cac7cdc48b8)

**Comment by NCBPFluffyBear** [comment]
I've put this issue on hold for too long.. but here is my solution: Since it takes less than 1 copper dust to create 1 copper wire, I will round it up to be 1 copper dust = 1 wire (vs the current implementation where 3 copper dust = 1 wire)
