### ISSUE TITLE
The fluffy  cannot store items

### ISSUE THREAD

**Issue by lyouismi** [NCBPFluffyBear/FluffyMachines#140]
## Description (Required)

![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/140181980/34e234b6-7c20-4c7e-89fc-557b74577595)

## Steps to reproduce the Issue (Required)

I forced the Chunk to load,After leaving the server for a period of time，The fluffy Barrels is damaged and unable to store or retrieve items，But quick retrieval and quick storage are normal

## Server Log / Error Report

This is a bug. I will also encounter this bug after restarting the testing server，
## Environment (Required)

 - Minecraft Version:1.19.4
 - CS-CoreLib Version:
 - Slimefun Version:2023.06
 - FluffyMachines Version: RC27+
I am using a translated version, which may be different from the official version

**Comment by lyouismi** [comment]
The version I am using：https://github.com/SlimefunGuguProject/FluffyMachines/blob/master/src/main/java/io/ncbpfluffybear/fluffymachines/items/Barrel.java

**Comment by NCBPFluffyBear** [comment]
Are there any errors in the console? Also, how are you trying to store and retrieve items? Manually though the GUI, using cargo, or both?

**Comment by lyouismi** [comment]
I used quick retrieval and quick storage to store and retrieve items. The console has been out of record for too long. After a long time, we can no longer find the console records at that time. Now I have avoided this bug by using ban items and updating to the latest version of Slimefun.
