### ISSUE TITLE
trigger-other-plugins no longer works

### ISSUE THREAD

**Issue by TheJohnLong** [NCBPFluffyBear/FluffyMachines#142]
## Description

The trigger-other-plugins option no longer seems to trigger events that [Jobs reborn](https://github.com/Zrips/Jobs) can pickup

## Expected behavior (Required)
Experience for every block broken with the explosive pickaxe / lumber axe

## Actual behavior
Only the experience for the targeted block is given

Mining with a vanilla Netherite pickaxe
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/5272660/3b8ea85a-8e58-4354-9d4e-670a54b7a7da)

Mining with an upgraded explosive pickaxe
![image](https://github.com/NCBPFluffyBear/FluffyMachines/assets/5272660/595bab24-8124-48bd-ad79-fc03efa14800)

## Environment (Required)
Minecraft Version: 1.20.1
Purpur git-Purpur-2062 (MC: 1.20.1)
Slimefun DEV - 1101 (git 37681caf)
Metrics-Module # 29 
Java 17
FluffyMachines vDEV - 130 (git 01c839cc)

**Comment by NCBPFluffyBear** [comment]
This looks like an issue caused by the other plugin. Please contact their developer to look into this, as I can't implement anything to restore that functionality.
