### ISSUE TITLE
TREE_GROWTH_ACCELERATOR bug

### ISSUE THREAD

**Issue by rukshan2004lk** [NCBPFluffyBear/FluffyMachines#151]
https://paste.walshy.dev/1Fw9SRPerif5 this is crash report

[bug video](https://www.mediafire.com/file/u3yb56ohy4rrjdg/0627.mov/file)

**Comment by NCBPFluffyBear** [comment]
Hey, the Tree Growth Accelerator is a part of Slimefun4, not FluffyMachines :)

**Comment by rukshan2004lk** [comment]
did you check the log file

**Comment by NCBPFluffyBear** [comment]
Yes, please check #bugs, I believe I found your source of confusion
