### ISSUE TITLE
Upgraded tools not compatible with AdvancedEnchantments

### ISSUE THREAD

**Issue by DarrienZ** [NCBPFluffyBear/FluffyMachines#154]
## Description (Required)
When enchanting Smelting or Trench enchantment on Upgraded Explosive Pickaxe, it will crash the server.

## Steps to reproduce the Issue (Required)
![image](https://github.com/user-attachments/assets/520aef71-9939-41a7-be88-df92cf3935a7)

## Expected behavior (Required)
It works fine with a normal explosive pickaxe.

## Server Log / Error Report
I can't paste it in sourcebin or pastebin. The file is too big.
[2024-09-06-2.log](https://github.com/user-attachments/files/16899219/2024-09-06-2.log)

## Environment (Required)

![image](https://github.com/user-attachments/assets/a4822d45-f88f-46ce-88cd-7999920f532c)

**Comment by DarrienZ** [comment]
Sorry it happens on all the tools

**Comment by NCBPFluffyBear** [comment]
Please change the 'trigger-other-plugins' flag in 'plugins/Slimefun/items.yml' to false and check if this issue still occurs. This option is default on so that players trigger McMMO for every block they break, but can cause issues like the one you are experiencing for other plugins.

**Comment by NCBPFluffyBear** [comment]
> Sorry it happens on all the tools

The mentioned toggle exists for the other tools too, make sure those are also changed to false!

**Comment by DarrienZ** [comment]
Alright, will try now

**Comment by DarrienZ** [comment]
Fixed! Thanks you
