### ISSUE TITLE
Dolly bypasses GriefPrevention and LockettePro

### ISSUE THREAD

**Issue by UDPSendToFailed** [NCBPFluffyBear/FluffyMachines#18]
## Description (Required)

The Dolly can be used to pick chests up from other player's claim, and it bypasses lock signs.

## Steps to reproduce the Issue (Required)

https://youtu.be/Zh-pIFmysLA
Right click a chest with Dolly inside a claim which you have no permission to. Possibly works on PlotSquared too.

## Expected behavior (Required)

Dolly can't pick up chests from GriefPrevention claims and doesn't bypass LockettePro.

## Server Log / Error Report

No errors.

## Environment (Required)

 - Minecraft Version: Paper v1_16_R2
 - CS-CoreLib Version: CS-CoreLib vDEV - 91 (git e42a05d1)
 - Slimefun Version: Slimefun vDEV - 690 (git 4c41650d)
 - FluffyMachines Version: FluffyMachines vDEV - 14 (git 7ce1f2ab)

**Comment by NCBPFluffyBear** [comment]
Whoops, forgot to mark that this was fixed by #21

**Comment by andris155** [comment]
This bug don't fixed in latest version.
