### ISSUE TITLE
auto ancient altar

### ISSUE THREAD

**Issue by 100petr** [NCBPFluffyBear/FluffyMachines#28]
## Description (Required)

Unable to create broken spawner
## Steps to reproduce the Issue (Required)

sf guide recipe:
![2020-10-08_15 13 19](https://user-images.githubusercontent.com/29830635/95463280-de958b00-0978-11eb-8917-54bdade5a965.png)
![2020-10-08_15 13 21](https://user-images.githubusercontent.com/29830635/95463294-e05f4e80-0978-11eb-91c9-7f907c437516.png)
![2020-10-08_15 13 22](https://user-images.githubusercontent.com/29830635/95463297-e1907b80-0978-11eb-83c7-943eb32e4101.png)

auto ancient altar:
![image](https://user-images.githubusercontent.com/29830635/95463441-0a187580-0979-11eb-9ff0-280980c8ca4d.png)
![image](https://user-images.githubusercontent.com/29830635/95463457-0f75c000-0979-11eb-9cbc-052a24b38fee.png)
![image](https://user-images.githubusercontent.com/29830635/95463486-156ba100-0979-11eb-9065-5a53013965e7.png)
It has energy
![2020-10-08_15 18 34](https://user-images.githubusercontent.com/29830635/95463865-99258d80-0979-11eb-8f3f-ff42cc597291.png)

## Expected behavior (Required)

A broken spawner is created
## Server Log / Error Report

No errors
## Environment (Required)

 - Minecraft Version: paper 1.16.3 #216
 - CS-CoreLib Version: DEV - 91
 - Slimefun Version: DEV - 705
 - FluffyMachines Version: DEV - 22
- SoulJars Version: DEV - 17

**Comment by NCBPFluffyBear** [comment]
This is just something that you will not be able to do, since it uses a dynamic recipe. Sorry

**Comment by 100petr** [comment]
Couldn't it really be added somehow? : /

**Comment by NCBPFluffyBear** [comment]
I have this coded, bug testing

**Comment by NCBPFluffyBear** [comment]
added in latest build
