### ISSUE TITLE
When break 1 000 000 blocks stored barrel cause server, client, and computer freeze

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#31]
## Description (Required)

When break 1 000 000 blocks stored barrel cause server, client dead.

## Steps to reproduce the Issue (Required)

1. Store over 1 000 000 block a barrel.
2. Break the barrel.
3. Everything freeze. Server, client, computer.

https://www.youtube.com/watch?v=5jZdy4rNySQ

## Expected behavior (Required)

Disable item drops when break the barrels.

## Environment (Required)

[17:26:05 INFO]: This Server uses the following setup of Slimefun:
[17:26:05 INFO]: Paper v1_16_R2
[17:26:05 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[17:26:05 INFO]: Slimefun vDEV - 729 (git 38bf2280)
[17:26:05 INFO]: Metrics build: #17
[17:26:05 INFO]: Backwards compatibility enabled!
[17:26:05 INFO]:
[17:26:05 INFO]: Installed Addons: (2)
[17:26:05 INFO]:  RestrictedCreative v2.4.4
[17:26:05 INFO]:  FluffyMachines vDEV - 30 (git fca125f9)

**Comment by poma123** [comment]
I'd rather cancel breaking the barrel if it has more than 27x64 (...or so) items in it.

**Comment by NCBPFluffyBear** [comment]
This is absolutely beautiful

**Comment by NCBPFluffyBear** [comment]
> I'd rather cancel breaking the barrel if it has more than 27x64 (...or so) items in it.

Id probably make it drop in 10k or 100k chunks if its over the limit

**Comment by NCBPFluffyBear** [comment]
A cap has been added in the latest update, Thank you for reporting!

**Comment by andris155** [comment]
@NCBPFluffyBear 
This fix is bad. If players break out the barrel more than once the server and client will freeze in the same way.

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=4pja5VIiPak

**Comment by poma123** [comment]
> I'd rather cancel breaking the barrel if it has more than 27x64 (...or so) items in it.

I still think this would be the best workaround.

**Comment by NCBPFluffyBear** [comment]
Literally anyone can do the same thing with chests

**Comment by NCBPFluffyBear** [comment]
> This fix is bad. 

If you have any solutions, feel free to tell me

I might cancel it for now, but we will see
