### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by Glichy** [NCBPFluffyBear/FluffyMachines#39]
I was looking through the recent commits and noticed this, shouldn't one of these be  MILK_BUCKET?
[https://github.com/NCBPFluffyBear/FluffyMachines/commit/b7eacdd9829527b624a70a41c9a585133d6e8524#diff-1f3e825d2e6d5244701c954058d4597aa1d041d9549516891c59355f7f4c5c7aR116](https://github.com/NCBPFluffyBear/FluffyMachines/commit/b7eacdd9829527b624a70a41c9a585133d6e8524#diff-1f3e825d2e6d5244701c954058d4597aa1d041d9549516891c59355f7f4c5c7aR116)

**Comment by NCBPFluffyBear** [comment]
ty, fixed
