### ISSUE TITLE
Backpack upgrade removed the fireproof

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#42]
## Description (Required)

If I upgrade the backpack removed fireproof when crafting.
Example.: Fireproof small backpack upgraded to backpack.

## Steps to reproduce the Issue (Required)

1. Make fireproof small backpack.
2. Craft fireproof small backpack to backpack.

<img width="523" alt="100394576-e6e77980-303d-11eb-985e-5ec0623e857b" src="https://user-images.githubusercontent.com/8324198/100760060-a5feb480-33f1-11eb-8c12-560dc4c30dbb.png">

3. Fireproof removed

<img width="494" alt="100394579-e9e26a00-303d-11eb-94ba-2d06b0f5a92e" src="https://user-images.githubusercontent.com/8324198/100760124-b6169400-33f1-11eb-85b1-9a2b3c0e0a48.png">

## Expected behavior (Required)

If I upgrade the backpack no removed fireproof when crafting.

## Environment (Required)

[16:25:10 INFO]: This Server uses the following setup of Slimefun:
[16:25:10 INFO]: Yatopia v1_16_R3
[16:25:10 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[16:25:10 INFO]: Slimefun vDEV - 761 (git ac7bb44d)
[16:25:10 INFO]: Metrics build: #17
[16:25:10 INFO]:
[16:25:10 INFO]: Installed Addons: (1)
[16:25:10 INFO]:  FluffyMachines vDEV - 48 (git 174f1cdb)

**Comment by NCBPFluffyBear** [comment]
All I can tell you for now is either don't fireproof it until you are done upgrading it or make multiple fireproof runes. I'm pretty sure the same thing happens with soulbound. The reason why I can't fix this is because upgrading the backpack physically makes a new item, there is no way to carry over metadata (including lore) over.

**Comment by andris155** [comment]
The Soulbound remove is fixed.
https://github.com/Slimefun/Slimefun4/issues/2574

**Comment by NCBPFluffyBear** [comment]
That is done through Slimefun's code during the crafting process. Since FluffyMachines is an addon, I can't modify something like that.
