### ISSUE TITLE
Disappearing barrels

### ISSUE THREAD

**Issue by 100petr** [NCBPFluffyBear/FluffyMachines#45]
## Description (Required)

The barrels are disappearing
## Steps to reproduce the Issue (Required)

The player wrote me in the morning that he put items in the barrel and disappeared. All day long, players have been reporting the disappearance of barrels.
## Expected behavior (Required)

The barrels will not disappear
## Server Log / Error Report

https://pastebin.com/YzMPXAay
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/102374129-4394df00-3fc1-11eb-9e5b-9f1d59c56c78.png)

**Comment by NCBPFluffyBear** [comment]
Working on this now, but for the future, please put in steps for reproduction. That really speeds up debugging.

**Comment by 100petr** [comment]
I didn't know much from the players myself, but thank you.
