### ISSUE TITLE
Outbound items from Barrels

### ISSUE THREAD

**Issue by Wirusiu** [NCBPFluffyBear/FluffyMachines#49]
https://imgur.com/a/vOObmrn

**Comment by NCBPFluffyBear** [comment]
This is a Slimefun cargo issue, not FluffyMachines. Issue is known, and items used to just be deleted. Biscuit decided dropping the items onto the ground was a "compromise". Also, you are lucky I knew the context of this issue. The next time you post a bug report like this without following the format, I will simply ignore it. It doesn't matter if you aren't a native english speaker, even google translate is better than simply posting an imgur link.

**Comment by NCBPFluffyBear** [comment]
I should also clarify that there probably won't be a fix for this issue besides a cargo overhaul. A "solution" to this would be to infused hopper these items back into the system.

**Comment by Wirusiu** [comment]
ok very thanks.
