### ISSUE TITLE
incompatibility with ColoredEnderChests 

### ISSUE THREAD

**Issue by 100petr** [NCBPFluffyBear/FluffyMachines#52]
## Description (Required)

Ender chest node do not take items from coloredenderchest (https://github.com/TheBusyBiscuit/ColoredEnderChests).
## Steps to reproduce the Issue (Required)

Place any chest from coloredenderchests
Try transferring items from it via the ender chest extraction node
It will transfer your private ender chest, not colored.
Video: https://youtu.be/TwFa5AR5dEI
## Expected behavior (Required)

The items in the coloredenderchest will be transferred.
## Server Log / Error Report

N/A
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/103441912-a89f3480-4c51-11eb-8e2d-164260de55bf.png)

**Comment by NCBPFluffyBear** [comment]
Colored ender chests are not actual ender chests, they are simply shared storages that mirror their inventory.
