### ISSUE TITLE
Soulbound Items uncraftable in the auto magic workbench

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FluffyMachines#56]
## Description (Required)

Crafting soulbound items in the automatic magic workbench isn't crafting items when the ingredient items are non stackable. For example, I tried to craft a soulbound helmet with 2 essence of afterlife and a diamond helmet but it would not craft.

## Steps to reproduce the Issue (Required)

Put the unstackable armor or tool or weapon in the center, and the essence of afterlife above and below and it will not craft the soulbound item.

## Expected behavior (Required)

Based on the recipe I expected it to craft the item.

## Server Log / Error Report

no erros

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: Dev 92
 - Slimefun Version: Dev 774
 - FluffyMachines Version: Dev 59

**Comment by NCBPFluffyBear** [comment]
When I saw this on discord, I thought you were referring to the auto ancient altar. This will be slightly more difficult since the recipe has air slots. It's still doable, but will take a bit more time.

**Comment by NCBPFluffyBear** [comment]
I think the solution for this is a bit too hacky, otherwise this machine would need an overhaul. Is there a practical reason for automating soulbound armor/tools?

**Comment by NCBPFluffyBear** [comment]
oops

**Comment by NCBPFluffyBear** [comment]
Feemed to not be an extremely important feature to implement.
