### ISSUE TITLE
Disabling the FLUFFYMACHINES_INFO item in Items.yml completely disables both categories.

### ISSUE THREAD

**Issue by MagmaBro123** [NCBPFluffyBear/FluffyMachines#58]
## Description (Required)
Disabling the "FLUFFYMACHINES_INFO" item/block in the Items.yml file, completely removes both categories for this addon.

## Steps to reproduce the Issue (Required)
Go into the Slimefun Items.yml file, and set "enabled: true" to "enabled: false" for FLUFFYMACHINES_INFO.

## Expected behavior (Required)
The item to be removed without the categories yeeting themselves from the guide.

## Server Log / Error Report
N/A

## Environment (Required)
![2021-01-10_11 03 36](https://user-images.githubusercontent.com/51277766/104132635-82555500-5333-11eb-9bcd-df5063e9d0ee.png)
![2021-01-10_11 03 38](https://user-images.githubusercontent.com/51277766/104132637-84b7af00-5333-11eb-898e-2d81fd63fb72.png)
Had to do 2 since MC's chat is not being nice.

**Comment by NCBPFluffyBear** [comment]
I was able to do this just fine
![image](https://user-images.githubusercontent.com/31554056/104133088-d289e280-5346-11eb-8415-65cf611760c3.png)

Could you please upload your items.yml to pastebin/hastebin and send a screenshot of your guide?

**Comment by MagmaBro123** [comment]
This also randomly occurs for no reason. Sometimes the categories appear, and sometimes aren't there.

GitHub hates .yml files, so using Dropbox.
https://www.dropbox.com/s/ikctfkg4xwv9j7p/Items.yml?dl=0

**Comment by NCBPFluffyBear** [comment]
Can I see the screenshot of the guide?

**Comment by MagmaBro123** [comment]
Start the server.
![2021-01-10_12 09 56](https://user-images.githubusercontent.com/51277766/104134154-ca2caa00-533c-11eb-8454-d7a430aab130.png)
![2021-01-10_12 10 07](https://user-images.githubusercontent.com/51277766/104134155-cac54080-533c-11eb-8382-8b51e0949a63.png)

**Comment by NCBPFluffyBear** [comment]
Never use reload. The reason reloading is discourage is not because of test server/real server, it is because of the way that items load in. In FluffyMachines, a custom glow enchant is used, which can not be registered twice. Therefore, by reloading it, you are blocking FluffyMachines from loading. Even without Slimefun, you shouldn't /reload since there is a change it can corrupt things.

**Comment by MagmaBro123** [comment]
Ah. Well, restarting does this same thing. Sometimes its there, sometimes its not.

**Comment by NCBPFluffyBear** [comment]
There should be something in console. Could u restart until it does not appear, and then send me your console logs?

**Comment by MagmaBro123** [comment]
I don't get any errors.

**Comment by NCBPFluffyBear** [comment]
That plugin failing to load is FluffyMachines. When a plugin fails to load, the plugin's contents wont show...
