### ISSUE TITLE
QuickShop reremake Incompability

### ISSUE THREAD

**Issue by GOLOKKU** [NCBPFluffyBear/FluffyMachines#64]
## Description (Required)
[Plugin QuickShop Reremake](https://www.spigotmc.org/resources/62575/)
You can break/steal other player chestshop using fluffy machine dolly

## Steps to reproduce the Issue (Required)
Video : 
[bug.mp4](https://cdn.discordapp.com/attachments/765741154989244458/802764959401377812/bug.mp4)

## Expected behavior (Required)
Cancel dolly pickup event to chest shop

## Server Log / Error Report
[latest.log](https://github.com/NCBPFluffyBear/FluffyMachines/files/5861584/latest.log)

## Environment (Required)

 - Minecraft Server Version: Yatopia-R0.1-SNAPSHOT 1.16.5
 - CS-CoreLib Version: DEV-79 (git ec5b4c24)
 - Slimefun Version: DEV - 795 (git 17fd2ec5)
 - FluffyMachines Version: DEV -64 (git 582f5de7)
 - Quickshop Reremake : 4.0.6.3

**Comment by NCBPFluffyBear** [comment]
The dolly checks for permissions, so there isn't much I can do there since Slimefun doesn't work with QuickShop Reremake permissions. If you want, you can disable the dolly in items.yml.
