### ISSUE TITLE
Superheated furnace error when break 2 times if stored too many items

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#65]
## Description (Required)

Superheated furnace error when break 2 times if stored too many items.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=hFHgItOjQNg

## Expected behavior (Required)

Superheated furnace no writes error when break 2 times if stored too many items.

## Server Log / Error Report

https://pastebin.com/V3QrFDW6

## Environment (Required)

[15:14:43 INFO]: This Server uses the following setup of Slimefun:
[15:14:43 INFO]: Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
[15:14:43 INFO]: Slimefun vDEV - 795 (git 17fd2ec5)
[15:14:43 INFO]: Metrics build: #19
[15:14:43 INFO]:
[15:14:43 INFO]: Installed Addons: (1)
[15:14:43 INFO]:  FluffyMachines vDEV - 64 (git 582f5de7)

**Comment by NCBPFluffyBear** [comment]
This is not a storage issue, the error occurred when trying to remove the lava armor stand. This would happen if you killed the armor stand.

**Comment by andris155** [comment]
If you break the Superheated furnace block when you store too many items, the armor stand removed, but the block does not break.

**Comment by andris155** [comment]
Watch the video, if you don't watched. I don't killed the armor stand.

**Comment by andris155** [comment]
The plugin removed the armor stand, and not me.

**Comment by NCBPFluffyBear** [comment]
Taken care of, will be released in next FM release.
