### ISSUE TITLE
Jobs reborn & Upgraded Lumber Axe

### ISSUE THREAD

**Issue by Explosivecoin** [NCBPFluffyBear/FluffyMachines#66]
## Description (Required)
logs broken with the Upgraded Lumber Axe don't contribute to Jobs reborn jobs points/money/exp like the Upgraded Explosive Pickaxe.

## Steps to reproduce the Issue (Required)
Use Advanced Lumber Axe on Tree
Observe that logs beyond the first don't count towards Jobs reborn points/money/exp

## Expected behavior (Required)
Every block broken by the Upgraded Lumber Axe contributes to Jobs reborn like the Upgraded Explosive Pickaxe does

## Server Log / Error Report
N/A

## Environment (Required)
 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: DEV - 92
 - Slimefun Version: RC - 19
 - FluffyMachines Version: DEV - 64

**Comment by NCBPFluffyBear** [comment]
Taken care of, will be released in next FM release.
