### ISSUE TITLE
NoCheatPlus block Fluffy wrench quick break

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#67]
## Description (Required)

The NoCheatPlus plugin block Fluffy wrench quick break.

## Steps to reproduce the Issue (Required)

1. Install the NoCheatPlus, Slimefun, and the FluffyMachines to the server.
2. Try use the Fluffy Wrench.
3. NoCheatPlus block Fluffy wrench quick break

## Expected behavior (Required)

NoCheatPlus no block Fluffy wrench quick break.

## Server Log / Error Report

(!) andris155 failed FastMine (Block: FURNACE) (151VL)
(!) andris155 failed FastMine (Block: PLAYER_HEAD) (46VL)

## Environment (Required)

Yatopia git-Yatopia-ver/1.16.5-21 (MC: 1.16.5)
Slimefun DEV - 811 (git 5edf6140)
Metrics-Module #21
Java 11

Installed Addons: (11)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  RestrictedCreative v2.4.6
  ExtraTools vDEV - 23 (git 9299a65c)
  PomaExpansion vDEV - 13 (git 78eb8cc5)
  SFCalc vDEV - 15 (git 6586cb3f)
  LiteXpansion vDEV - 124 (git 0e449831)
  SlimefunFix v1.1-SNAPSHOT
  EcoPower vDEV - 3 (git 18ba903d)
  ExtraGear vDEV - 12 (git 4570ea2c)
  FluffyMachines vDEV - 64 (git 582f5de7)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)

**Comment by NCBPFluffyBear** [comment]
Fixed, will be implemented next update.
