### ISSUE TITLE
Comment missing Paxel blocks here

### ISSUE THREAD

**Issue by NCBPFluffyBear** [NCBPFluffyBear/FluffyMachines#68]
I'll reply to each thing when they get fixed.

**Comment by AgentIce** [comment]
I've tested quite a few blocks, missing ones appear to be the following:

DARK_OAK_FENCE_GATE
CRIMSON_FENCE_GATE
WARPED_FENCE_GATE
OAK_FENCE_GATE
BIRCH_FENCE_GATE
JUNGLE_FENCE_GATE
ACACIA_FENCE_GATE

DARK_OAK_PLANS
CRIMSON_PLANKS
WARPED_PLANKS
OAK_PLANKS
BIRCH_PLANKS
JUNGLE_PLANKS
ACACIA_PLANKS

Our versions:
![image](https://user-images.githubusercontent.com/69111163/108558350-1256c900-72fa-11eb-9334-05e5b6660278.png)

**Comment by GallowsDove** [comment]
LECTERN missing

**Comment by GallowsDove** [comment]
Some more missing blocks, done some testing for you:

Axe:
Smithing Table
Loom
Cartography Table
Fletching Table
Barrel
Jukebox
Campfire
Bookshelf
All banners
Jack o'Lantern
Pumpkin
Melon
Composter
Beehive
Bee Nest
Note Block
Ladder
Cocoa Beans
Daylight Detector
Mushroom Blocks
Bamboo
Vine

Shovel doesn't seem to be missing any blocks.
