### ISSUE TITLE
Scythe break RestrictedCreative plugin creative protected crops

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#69]
## Description (Required)

The RestrictedCreative disable the block items dropped when break if placed out in the creative mode.

## Steps to reproduce the Issue (Required)

1. Use the Scythe on the creative placed crops.
2. The Scythe breaks the RestrictedCreative block protection and crops dropped to floor.

## Expected behavior (Required)

The Scythe no breaks the RestrictedCreative block protection.

## Environment (Required)

[21:15:30 INFO]: This Server uses the following setup of Slimefun:
Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Installed Addons: (4)
  RestrictedCreative v2.4.6
  SlimefunFix v2.0
  LiteXpansion vDEV - 125 (git 96d1cf20)
  FluffyMachines vDEV - 64 (git 582f5de7)

**Comment by NCBPFluffyBear** [comment]
https://github.com/Slimefun/Slimefun4/wiki/Protection-Plugins

RestrictedCreative is not a listed supported protection plugin

**Comment by andris155** [comment]
No API for Scythe that I can use to fix protection for RestrictedCreative?

**Comment by NCBPFluffyBear** [comment]
Does RestrictedCreative work on base SF tools like the explosive pickaxe?

**Comment by andris155** [comment]
Yes they are supported by the RestrictedCreative plugin.

**Comment by NCBPFluffyBear** [comment]
From what I can see, my code supports protection plugins. Can you send a video of you breaking protected crops with the scythe vs breaking protected crops with the explosive pickaxe?

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=LJ2_ikiXX4Y

**Comment by NCBPFluffyBear** [comment]
Ok I finally understand what you mean. The issue is that the scythe can be used to obtain items that you want to prevent players from getting in creative mode. From what you told me, you mentioned block protection, so I thought you meant that you didn't want the crops to break in the first place. I'll look into this issue.

**Comment by NCBPFluffyBear** [comment]
Did you happen to do these: 
![image](https://user-images.githubusercontent.com/31554056/108094834-d941fe80-7044-11eb-8552-1256e9bbd32a.png)

**Comment by andris155** [comment]
?

**Comment by NCBPFluffyBear** [comment]
Did you do them? That is from the RestrictedCreative Spigot page.

**Comment by andris155** [comment]
Yes I changed these settings in Items.yml file.

**Comment by NCBPFluffyBear** [comment]
Did you already do them previously or did you just do them because I posted it?

**Comment by NCBPFluffyBear** [comment]
I need specifics since RestrictedCreative is a paid plugin and I can't do any testing with it.

**Comment by andris155** [comment]
Since my server is disabled for explosion items I do not use this settings. But as you can see in the video it works regardless.
RestrictedCreative has a good api that can be used to check if something has been placed down in a creative mode. For some extra protection, I made my own Slimefun addon. I tried cancel the Slimefun playerinteractevent with the Slimefun api, but it does not work. The Scythe removed block when this event canceled.

**Comment by NCBPFluffyBear** [comment]
There is no difference between the way the Explosive Pickaxe and the Scythe break/drop blocks, which makes me think that RestrictedCreative needs to add support for FM, not the other way around. The reason I asked you about the settings was because I was testing if RestrictedCreative used that itemsetting to stop item drops.

**Comment by andris155** [comment]
The Scythe does not have call-explosion-event setting currently.

**Comment by NCBPFluffyBear** [comment]
I am aware, which is why I was asking about the itemsetting.

**Comment by andris155** [comment]
If you add call-explosion-event setting to Scythe maybe fixing this problem.

**Comment by NCBPFluffyBear** [comment]
As we determined earlier, that is not the problem. You said yourself that you did not need to turn that setting on for the pickaxe, which means it has nothing to do with this issue.

**Comment by andris155** [comment]
I said: I don't use this on my server because Explosion tools is disabled.
But on my test server I enabled this setting (call-explosion-event setting). If this setting I disabled the Explosion tools protection not work.

**Comment by NCBPFluffyBear** [comment]
Okay, but there's another problem: The scythe doesn't explode anything. Calling an explosion event wouldn't make sense. Also... Are you sure you had it enabled? Looking at the video it looks disabled to me.

**Comment by andris155** [comment]
The call-explosion-event setting enabled on the video. I tested with disabled setting, and the creative protection not work with Explosion tools.

**Comment by NCBPFluffyBear** [comment]
I'll just make the scythe not drop blocks when the holder is in creative.

**Comment by NCBPFluffyBear** [comment]
Implemented d5ed4a5

**Comment by andris155** [comment]
Thanks!
