### ISSUE TITLE
Dolly remove the LockettePro protected chests if no permission to this

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#70]
## Description (Required)

Dolly remove the LockettePro protected chests if no permission to this.

## Steps to reproduce the Issue (Required)

1. Click with Dolly to the LockettePro protected chest if no permission.
2. Dolly removed the chest and the private sign destroyed.

## Expected behavior (Required)

Dolly no remove the LockettePro protected chests if no permission to this.

## Environment (Required)

[21:15:30 INFO]: This Server uses the following setup of Slimefun:
Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Installed Addons: (4)
  RestrictedCreative v2.4.6
  SlimefunFix v2.0
  LiteXpansion vDEV - 125 (git 96d1cf20)
  FluffyMachines vDEV - 64 (git 582f5de7)

**Comment by NCBPFluffyBear** [comment]
https://github.com/Slimefun/Slimefun4/wiki/Protection-Plugins

It looks like LockettePro is not supported

**Comment by andris155** [comment]
No API for Dolly that I can use to fix protection for LockettePro?

**Comment by NCBPFluffyBear** [comment]
This is a Slimefun protection related issue. Try locking an electric smeltery using lockette and opening it.

**Comment by andris155** [comment]
Slimefun supported the very outdated Lockette. I don't understand why they don't support the newer better LockettePro plugin.

**Comment by NCBPFluffyBear** [comment]
Put in an issue on the SF github for that.

**Comment by andris155** [comment]
I already putted.
https://github.com/Slimefun/Slimefun4/issues/2453

**Comment by NCBPFluffyBear** [comment]
This will be handled by LockettePro.
