### ISSUE TITLE
Auto Ancient Altar cargo error

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#71]
## Description (Required)

Auto Ancient Altar writes error when use with cargo network.

## Steps to reproduce the Issue (Required)

1. Use Auto Ancient Altar with cargo network.

## Expected behavior (Required)

Auto Ancient Altar no writes error when use with cargo network.

## Server Log / Error Report

https://pastebin.com/31bsVRhr

## Environment (Required)

[12:57:34 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"a539774" (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Installed Addons: (11)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  RestrictedCreative v2.4.6
  ExtraTools vDEV - 24 (git 791c7468)
  PomaExpansion vDEV - 15 (git f4bb6859)
  SlimefunFix v2.0
  SFCalc vDEV - 15 (git 6586cb3f)
  LiteXpansion vDEV - 128 (git 3d1408a5)
  EcoPower vDEV - 3 (git 18ba903d)
  ExtraGear vDEV - 12 (git 4570ea2c)
  FluffyMachines vDEV - 65 (git a7af4837)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)

**Comment by NCBPFluffyBear** [comment]
I can't reproduce this. What were you trying to cargo in? How many? What was inside the altar?

**Comment by andris155** [comment]
![2021-02-22_16 39 19](https://user-images.githubusercontent.com/8324198/108732084-83ca8d80-752d-11eb-96cb-f4cbb81977f2.png)
This system cause this error.

**Comment by andris155** [comment]
![2021-02-22_16 41 54](https://user-images.githubusercontent.com/8324198/108732163-95139a00-752d-11eb-9b7d-d68637f2cfd3.png)

**Comment by andris155** [comment]
![2021-02-22_16 47 43](https://user-images.githubusercontent.com/8324198/108732269-b2e0ff00-752d-11eb-88de-732ce637f961.png)

**Comment by andris155** [comment]
I successfully reproduced this error in my test server with this simple system.
![2021-02-22_17 11 28](https://user-images.githubusercontent.com/8324198/108735745-318b6b80-7531-11eb-8481-21647aa165f9.png)

**Comment by andris155** [comment]
I successfully reproduced this error in my test server with this simple system.
![2021-02-22_17 14 15](https://user-images.githubusercontent.com/8324198/108735982-71eae980-7531-11eb-96a6-191d2869a52d.png)

**Comment by NCBPFluffyBear** [comment]
> I can't reproduce this. What were you trying to cargo in? How many? What was inside the altar?

**Comment by NCBPFluffyBear** [comment]
Fixed cf423da

**Comment by andris155** [comment]
Thanks!
