### ISSUE TITLE
Plugin not enable when update the slimefun

### ISSUE THREAD

**Issue by xMikux** [NCBPFluffyBear/FluffyMachines#72]
## Description (Required)
The new thing break something?

## Steps to reproduce the Issue (Required)
Install Slimefun DEV - 820 and FluffyMachines

## Expected behavior (Required)
Don't have error, and enable the addon.

## Server Log / Error Report
https://pastebin.com/4g5YXydw

## Environment (Required)

![image](https://user-images.githubusercontent.com/26039249/108827160-39661100-7600-11eb-8d48-3fa8210f6620.png)

 - Minecraft Version: git-Paper-487 (MC: 1.16.5)
 - CS-CoreLib Version:
 - Slimefun Version:  DEV - 820 (git 338fe0f8)
 - FluffyMachines Version: vDEV - 65 (git a7af4837)

**Comment by NCBPFluffyBear** [comment]
This is an issue with Slimefun, and it should be fixed soon. I'll leave this open in case other people see the same issue.

**Comment by NCBPFluffyBear** [comment]
Fixed cf423da
