### ISSUE TITLE
Barrels dissapear on items entering via Cargo Management

### ISSUE THREAD

**Issue by TheonlyTazz** [NCBPFluffyBear/FluffyMachines#75]
## Description (Required)
Barrels dissapear when using Cargo Management to input items

## Steps to reproduce the Issue (Required)
1) Setup a Cargo Network
2) have items to import
3) I used advanced output nodes on the Barrels
4) as soon as an item gets inputted via the input chest to the output barrel, the barrel just dissapears

## Expected behavior (Required)
I'd have expected the items to go into the barrel as normally. using a hopper works fine, although limiting the throughput

## Server Log / Error Report

No error report

## Environment (Required)

 - Minecraft Version: 1.16.5-R0.1-SNAPSHOT
 - CS-CoreLib Version: Can't tell, not the Server Admin but server only running for a week
 - Slimefun Version: DEV - 821 (git 6533b502)
 - FluffyMachines Version: Build #65
 i cannot run `/sf versions` as i dont have "permissions"

**Comment by Boomer-1** [comment]
Tazz, this is a known issue with Cargo. This isn't a fluffy plugin issue.

**Comment by TheonlyTazz** [comment]
Actually this issue was resolved by Fluffy, it was just the lava under my cobble floor burning up the Beehive block used for the barrel, could be replaced back by a block placer

Closing issue.
