### ISSUE TITLE
Ender Chest Extraction Node has no texture.

### ISSUE THREAD

**Issue by MagmaBro123** [NCBPFluffyBear/FluffyMachines#78]
## Description (Required)
Title.

## Steps to reproduce the Issue (Required)
Install the plugin.

## Expected behavior (Required)
The extraction node to have a texture.

## Server Log / Error Report
N/A

## Environment (Required)
![2021-03-04_13 10 51](https://user-images.githubusercontent.com/51277766/110039828-a95a5280-7cf6-11eb-8796-3cd70f98804a.png)
![2021-03-04_13 10 53](https://user-images.githubusercontent.com/51277766/110039833-ac554300-7cf6-11eb-9e61-06244d936360.png)

![2021-03-04_15 33 52](https://user-images.githubusercontent.com/51277766/110039893-c4c55d80-7cf6-11eb-9de3-0bf570c98857.png)

**Comment by NCBPFluffyBear** [comment]
Did you use /reload? 
Try restarting your server. Just popped into a test server and a live server running v68 and they both have textures.

**Comment by GallowsDove** [comment]
I can confirm this bug on v68, without using reload or anything.

**Comment by MagmaBro123** [comment]
> Did you use /reload?
> Try restarting your server. Just popped into a test server and a live server running v68 and they both have textures.

Not at all. Restarted twice. Read @GallowsDove's comment.

**Comment by NCBPFluffyBear** [comment]
What the heck... the link doesn't work for me either, but its still showing up in game. Can you guys try running 67 or earlier and seeing what happens?

**Comment by MagmaBro123** [comment]
Build 67 of FM, nope

**Comment by NCBPFluffyBear** [comment]
earlier versions? i hopped onto a couple of servers and the texture are all working there too. Ill probably reupload the skin later but the next build might not come out for a while...

**Comment by MagmaBro123** [comment]
Well, Build 60 or below the category item doesn't appear (I didn't reload... -_-), and Build 61 still has no texture

**Comment by NCBPFluffyBear** [comment]
> I can confirm this bug on v68, without using reload or anything.
> 
> if you input the hash into link that should provide the texture, you can see that it leads to NOT FOUND
> http://textures.minecraft.net/texture/e707c7f6c3a056a377d4120028405fdd09acfcd5ae804bfde0f653be866afe39
> 
> example of working texture (watering can)
> http://textures.minecraft.net/texture/6484da45301625dee79ae29ff513efa583f1ed838033f20db80963cedf8aeb0e

Just revisited these links, the texture works now. @MagmaBro123, Can you confirm that the texture works for you in game and if so, close this issue?

**Comment by NCBPFluffyBear** [comment]
No response, and it looks fine to me. Closing
