### ISSUE TITLE
Fireproof Rune does not active when tossed on armor / tools on ground

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FluffyMachines#79]
## Description (Required)

I tossed a diamond chestplate on the ground, and a fireproof rune on top of it. They both just sat there and it never engaged.

## Steps to reproduce the Issue (Required)

Toss armor on ground, and rune. Nothing happens.

## Expected behavior (Required)

The rune to attach itself to the armor. Now, Thezerix and I tried multiple combinations on our servers. We both are able to confirm something in Dynatech is interferring. I'm also submitting this to Dynatech so she's aware as well.

## Server Log / Error Report

No errors in log

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version: dev 826
 - FluffyMachines Version: 68

**Comment by GallowsDove** [comment]
After some more testing, it appears that DynaTech sometimes prevents even regular Soulbound rune from firing.

**Comment by NCBPFluffyBear** [comment]
I believe this was fixed in DynaTech- if you can no longer reproduce this, please close this issue. Ty

**Comment by Boomer-1** [comment]
it is working perfectly now, thanks
