### ISSUE TITLE
Advanced Disenchanter is not working.

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FluffyMachines#81]
## Description (Required)

Currently the advanced enchanter is, but the disenchanter, when given a tool with an enchant and a book does not start up when powered. I used a diamond axe with efficiency 5. 

## Steps to reproduce the Issue (Required)

place advanced disenchanter
place a book and an enchanted tool in it
nothing happens.

## Expected behavior (Required)

the disenchanter to remove the enchant.

## Server Log / Error Report

no errors in console

## Environment (Required)

 - Minecraft Version: 1.16.15
 - CS-CoreLib Version: removed
 - Slimefun Version: Dev 833
 - FluffyMachines Version: Dev 68

**Comment by NCBPFluffyBear** [comment]
Won't be able to test this issue for about 2 days, could you send me a video of this?

**Comment by Boomer-1** [comment]
Here's the link to the video

https://youtu.be/8hgNsdWLQHs

**Comment by NCBPFluffyBear** [comment]
That's InfinityExpansion

**Comment by Boomer-1** [comment]
omg i'm a dufus. sorry bout that Fluffy. Don't know how I got that mixed up.
