### ISSUE TITLE
Error occurred while enabling FluffyMachines vDEV - 68

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#82]
## Description (Required)

The FluffyMachines no load with Slimefun DEV - 841

## Steps to reproduce the Issue (Required)

Start server with Slimefun DEV - 841 and FluffyMachines vDEV - 68.

## Expected behavior (Required)

FluffyMachines works perfectly with Slimefun DEV - 841

## Server Log / Error Report

https://pastebin.com/PQeM9RFT

## Environment (Required)

Tuinity git-Tuinity-"44e8e5d" (MC: 1.16.5)
Slimefun DEV - 841 (git a4521a2d)
Metrics-Module #21
Java 11

Installed Addons: (17)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 25 (git 209f9078)
  PomaExpansion vDEV - 15 (git f4bb6859)
  FoxyMachines v1.0.0
  EcoPower vDEV - 3 (git 18ba903d)
  HotbarPets vDEV - 36 (git 71e1a5e7)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 32 (git e108f086)
  InfinityExpansion vDEV - 93 (git 69b78a0f)
  RestrictedCreative v2.4.6
  SFCalc vDEV - 2 (git da4a9d46)
  LiteXpansion vDEV - 138 (git 004e3c61)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  MobCapturer vDEV - 15 (git a42c9e0c)
  TranscEndence vDEV - 23 (git c7ddc06a)
  FluffyMachines vDEV - 68 (git 54fdd26b)
  GeneticChickengineering v1.0.9

**Comment by mrcoffee1026** [comment]
Confirmed:
ProfElementsToday at 9:50 AM
FluffyMachines need to use the new ItemSetting stuff. Report it to the bug tracker

**Comment by NCBPFluffyBear** [comment]
aware of the issue, but ran into some problems with barrels when updating. trying to get that fixed rn.

**Comment by NCBPFluffyBear** [comment]
Fixed in latest
