### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by 100petr** [NCBPFluffyBear/FluffyMachines#84]
## Description (Required)

Plugin does not load
## Steps to reproduce the Issue (Required)

Update to the latest version (70 (git 628d95db)
Start server
## Expected behavior (Required)

The plugin will load
## Server Log / Error Report

Error: https://pastebin.com/HN3HSjeR
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/111839963-f0059a80-88fb-11eb-9f6f-6481e38bca39.png)

**Comment by NCBPFluffyBear** [comment]
Aware, working on it rn

**Comment by NCBPFluffyBear** [comment]
Fixed in 2f95831
