### ISSUE TITLE
Auto Ancient Altar & spawners

### ISSUE THREAD

**Issue by bobhenl** [NCBPFluffyBear/FluffyMachines#85]
## Description (Required)

Hi, I want to report that repairing broken spawners don't work in the auto ancient altar. AS I saw, there was already a problem with it in the past https://github.com/NCBPFluffyBear/FluffyMachines/issues/28.

## Steps to reproduce the Issue (Required)

![image](https://user-images.githubusercontent.com/18662086/113735299-6972fa80-96fc-11eb-903f-555abbdab3f6.png)

![image](https://user-images.githubusercontent.com/18662086/113735335-72fc6280-96fc-11eb-952d-9ab11d6abca7.png)

![image](https://user-images.githubusercontent.com/18662086/113735356-77288000-96fc-11eb-943c-bc14e4607e25.png)

![image](https://user-images.githubusercontent.com/18662086/113735366-7859ad00-96fc-11eb-9157-5f6dc192f6b9.png)

![image](https://user-images.githubusercontent.com/18662086/113735480-958e7b80-96fc-11eb-9864-a8eed3dca39f.png)

![image](https://user-images.githubusercontent.com/18662086/113735498-97f0d580-96fc-11eb-9b3c-e40c3156e1e9.png)

https://media.discordapp.net/attachments/624966637816381440/828640363115577364/unknown.png

## Expected behavior (Required)

The spawner should be probably repaired like in a normal ancient altar.
## Server Log / Error Report

Anything.

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: -
 - Slimefun Version: 869 (git 18139bb5)
 - FluffyMachines Version: 74 (git 8da3ae26)

**Comment by NCBPFluffyBear** [comment]
Fixed 10ca209
