### ISSUE TITLE
Error：Recipe must have non-AIR result.

### ISSUE THREAD

**Issue by a934990825** [NCBPFluffyBear/FluffyMachines#87]
## Environment (Required)

 - Minecraft Version:1.16.5
 - CS-CoreLib Version:*
 - Slimefun Version:4.9
 - FluffyMachines Version:last 

minecraft server version 1.16.5
This server is running Paper version git-Paper-603 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error occurred while enabling FluffyMachines vEFI - 48 (git 75e5c753) (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.

This is the branch version, and your version also prompts this.

**Comment by NCBPFluffyBear** [comment]
My version does not have this issue.

**Comment by a934990825** [comment]
I've found the reason. It's a conflict with crafting++ conflict

**Comment by a934990825** [comment]
Using idea build, do not output dev in classes

**Comment by NCBPFluffyBear** [comment]
Sending an an exception without a stacktrace isn't really helpful...

**Comment by NCBPFluffyBear** [comment]
No response for over a week.
