### ISSUE TITLE
When player sneak, levitation effect get removed whether he wear a helicopter helmet or not

### ISSUE THREAD

**Issue by yumjunstar** [NCBPFluffyBear/FluffyMachines#88]
## Description (Required)

You can check this problem easily
Title is description
When player sneak, levitation effect get removed whether he wear a helicopter helmet or not
## Steps to reproduce the Issue (Required)

1. effect give playername levitation 1000 1
2. press shift key
3. levitation effect will remove
## Expected behavior (Required)

levitation effect shouldn't be removed
## Server Log / Error Report

There is no error
## Environment (Required)

You can simply reproduce by installing slimefun4 and FluffyMachines
![image](https://user-images.githubusercontent.com/24960675/116812524-17ea4e00-ab8a-11eb-8128-5ceb34d174f5.png)
 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - FluffyMachines Version:

**Comment by NCBPFluffyBear** [comment]
Fixed in 33ea928
