### ISSUE TITLE
Electric Dust Fabricator disappears

### ISSUE THREAD

**Issue by Schwi-Dol** [NCBPFluffyBear/FluffyMachines#90]
## Description
When placed on the floor with power on, the Electric Dust Fabricator simply consumes the cobblestone and disappears

## Steps to reproduce the Issue
Place the item on the floor, connected to power connectors and add 5 to 10 cobblestones, the item will disappear for no reason

Link: https://youtu.be/pAJelQlkbn8

## Expected behavior
It should consume the stone and result in ore dust

## Server Log / Error Report

Log: https://pastebin.com/Wx7TMGAE

## Environment

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: idk
 - Slimefun Version: Dev-925
 - FluffyMachines Version: vDEV-81

**Comment by NCBPFluffyBear** [comment]
[14:32:28 ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.

**Comment by Schwi-Dol** [comment]
here: https://pastebin.com/xXN5kFgL

**Comment by NCBPFluffyBear** [comment]
Fixed in latest
