### ISSUE TITLE
Duplication glitch with Fluffy Barrels

### ISSUE THREAD

**Issue by pHI10S0PH3RKING** [NCBPFluffyBear/FluffyMachines#91]
## Description (Required)

When a barrel's type is set to a shulker containing items the barrel will take any shulker from the players inventory via insert all regardless of its contents and will then allow withdrawal of duplicates of the set item.  
## Steps to reproduce the Issue (Required)

 put 3 shulkers into any fluffy barrel containing the same items and quantities then fill inventory with other shulkers (I don't know if they need to be the same color as i only tested with undyed shulkers) then click insert all and all shulkers will be taken and added as stacks of the original shulker type. Next withdraw either one at a time or via extract all and you will have shulkers containing the duped items.
## Expected behavior (Required)

Barrel would not accept shulkers containing items that did not match its original and as such would not add stacks of the original to the barrels inventory and thus A) delete all items in shulkers in players inventory and B) allow items to be duped by inserting empty shulkers.
## Server Log / Error Report

I'm Just a player on the server where I observed the behavior so I don't have access to the logs but I've messaged the admin and asked that they be added to this bug report
## Environment (Required)

Again I'm just a player and don't have access to the /sf commands but ill try to add what i cna see from the guide and have admin update later 
 - Minecraft Version: 1.16.5-R0.1-Snapshot
 - CS-CoreLib Version:
 - Slimefun Version: Dev-927 (git cf362f7c)
 - FluffyMachines Version: Dev-82 (git 63e6353b)

**Comment by NCBPFluffyBear** [comment]
Is this only for the insert button or does it also work with manually putting them in?

**Comment by pHI10S0PH3RKING** [comment]
Only inserting via the button will add inappropriate shulkers putting them in manually they just sit there in the input slot

**Comment by NCBPFluffyBear** [comment]
ty for report

**Comment by kirin-3** [comment]
Hello, I am the server owner of the said server.

There are no warnings or errors in the console.

FluffyMachines Version: Dev-82
Slimefun Version: Dev-928
Minecraft Version: Paper-587
