### ISSUE TITLE
Addition of auto crafter (enhanced crafting recipe)

### ISSUE THREAD

**Issue by Shadowboy00** [NCBPFluffyBear/FluffyMachines#93]
Hi is it possible to add an auto crafter for enhanced crafting recipe? Currently there is no automation for this yet, the one provided in the cargo management section is hard to use for automation. Thanks for your time.

**Comment by NCBPFluffyBear** [comment]
It is possible but I would rather not. The reason the vanilla autocrafter exists is because it was introduced before the SF vanilla autocrafter.

**Comment by Shadowboy00** [comment]
alright, it'd be cool though.
