### ISSUE TITLE
Fluffy machines not being able to start in the latest version

### ISSUE THREAD

**Issue by Rojiza** [NCBPFluffyBear/FluffyMachines#95]
## Description 
 Hi there, I have updated both SlimeFun and FluffyMachines to their latest version 
 It doesnt start and it will not show up in the /sf guide
 This happened even before updating slimedun, I tried to update both plugins (sf and fluffy machines)hoping it would get fixed but it didnt 

## Steps to reproduce the Issue (Required)
We just started the server and fluffy machines was gone

## Expected behavior (Required)
What did you expect to happen?
to start and be enabled with the other addons

## Server Log / Error Report
Server Log
https://pastebin.com/GwMV1AgV

## Environment (Required)
https://imgur.com/wM8kySV

 - Minecraft Version: 1.17.1
 - CS-CoreLib Version:
 - Slimefun Version: Slimefun4 RC-28.jar
 - FluffyMachines Version:   DEV 89 (git 2c269).jar

**Comment by NCBPFluffyBear** [comment]
Fixed in latest version
