### ISSUE TITLE
FluffyBarrels Trashcan Toggle

### ISSUE THREAD

**Issue by Rensura** [NCBPFluffyBear/FluffyMachines#96]
The idea of this feature is to make an addition to the UI of FluffyBarrels. The feature would consist of another button being added beside the toggle hologram button, and it would be the Trashcan Toggle.

The idea of the Trashcan toggle is to make it so once a barrel is full on an item, any item put into the input slot would be deleted, this would avoid clogging of automatic dust farms.

**Comment by NCBPFluffyBear** [comment]
Implemented
