### ISSUE TITLE
Fluffy Wrenchs recipe couldn't be set in the Auto-Crafter (Enchanced) because it removes the crafter

### ISSUE THREAD

**Issue by andris155** [NCBPFluffyBear/FluffyMachines#97]
## Description (Required)

Fluffy Wrenchs recipe couldn't not be set in the Auto-Crafter (Enchanced) because it removes the crafter when I shift + right clicked to the crafter.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=329QnhPJss4

## Expected behavior (Required)

Fluffy Wrenchs no remove the Auto-Crafter (Enchanced) Slimefun machine.

## Environment (Required)

Paper git-Paper-310 (MC: 1.17.1)
Slimefun DEV - 976 (git fe9d11d8)
Metrics-Module #28
Java 16

Installed Addons: (25)
  ExtraTools vDEV - 31 (git abdc1514)
  FoxyMachines vDEV - 51 (git 3493db25)
  DynaTech vDEV - 133 (git f1901252)
  InfinityExpansion vDEV - 123 (git f5f22167)
  RestrictedCreative v2.5.2
  CMILib v1.0.3.11
  ElectricSpawners vDEV - 23 (git 6ec96773)
  EMC2 vDEV - 11 (git 89b4400a)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 6 (git 347684ce)
  SlimeTinker vDEV - 40 (git da71fccb)
  Galactifun vDEV - 16 (git 48e51710)
  FluffyMachines vDEV - 90 (git b36089e8)
  ChestTerminal vDEV - 44 (git 3115957d)
  PomaExpansion v1.3.2
  SlimefunFix v3.3
  AlchimiaVitae vDEV - 12 (git d27baab4)
  SlimefunWarfare vDEV - 65 (git 0937c8d6)
  EcoPower vDEV - 5 (git 5c1ecd68)
  Liquid vDEV - 13 (git 6b71d3b3)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 14 (git 4b1259c7)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)
  SlimyRepair vDEV - 4 (git 790c41cb)

**Comment by NCBPFluffyBear** [comment]
Do you have an idea on how to fix this? I can't just disable the wrench on the crafters in case someone wants to actually break them.

If not, here's a janky solution:
https://youtu.be/cp2o1MLBW_8

1. Put wrench in offhand
2. Sneak and hold right click so it starts to repetitively interact with the block you are looking at
3. Move wrench back into your mainhaind via hotkey
4. Look at the auto crafter
