### ISSUE TITLE
Ancient Auto Altar Spawners bug (SoulJars compatibility)

### ISSUE THREAD

**Issue by Straikerinos** [NCBPFluffyBear/FluffyMachines#98]
## Description (Required)
When trying to create a broken spawner from Auto Altar, there was a bug and the altar created some "custom" spawner and not the spawner listed in the Slimefun guide book. This means that this spawner cannot be repaired and a Reinformaced spawner created

## Steps to reproduce the Issue (Required)
Spawner must be crated & fixed in the Ancient Altar (multi-block)
https://www.youtube.com/watch?v=1R68ZRNPbSc

## Expected behavior (Required)
That will create the spawner listed in the slimefun guide (SoulJars)

## Environment (Required)
![obrazek](https://user-images.githubusercontent.com/43417249/137592503-3e3ab734-25c7-4a44-aa8c-f1fe905aa7ac.png)

 - Minecraft Version: Airplane 1.17.1
 - CS-CoreLib Version: none
 - Slimefun Version: 982
 - FluffyMachines Version: 90

**Comment by NCBPFluffyBear** [comment]
> Spawner must be crated & fixed in the Ancient Altar (multi-block)

Soul Jars created spawners are bugged in general, this is not a FluffyMachines issue.

https://github.com/TheBusyBiscuit/SoulJars/issues/23
